### ISSUE TITLE
PlayBack Failure

### ISSUE THREAD

**Issue by fclante** [mintsoft/kodi.plugin.video.pluralsight#11]
As of yesterday I can no longer play any videos. I can login and browse courses. that's it.

In the kodi.log it Throws a VideoNotFoundError - so the video_url field is never set.

**Comment by mintsoft** [comment]
Hi @fclante 
Thanks for the report, I've just confirmed this on my install too. I'll have a crack at it later on today hopefully

**Comment by lestrela** [comment]
Any news on this?

Regards
Leo

**Comment by mintsoft** [comment]
@lestrela This is bigger than I hoped unfortunately; it looks like a significant portion of Pluralsight's API structured has changed. Hopefully I'll find some time to kick it again soon

**Comment by lestrela** [comment]
What a pity! Right now that I was taking my rasp pi all over just to study
at Pluralsight.
Good luck. I hope the problem is simple to fix.
Thanks for the answer!

Cheers!!

Leo

2017-03-28 15:59 GMT-03:00 Rob Emery <notifications@github.com>:

**Comment by mintsoft** [comment]
Good news, I've got this working again. I just need to clean the code up then I can release it

**Comment by mintsoft** [comment]
Just waiting for KODI to accept the PR (https://github.com/xbmc/repo-plugins/pull/1088) which will release 1.1.3

**Comment by lestrela** [comment]
Great Rob!!

Yiu are the man!!!

Em domingo, 2 de abril de 2017, Rob Emery <notifications@github.com>
escreveu:

**Comment by mintsoft** [comment]
Fixed in 1.1.3; now released

**Comment by lestrela** [comment]
Great Rob. I'm going to test ASAP


2017-04-06 15:54 GMT-03:00 Rob Emery <notifications@github.com>:

**Comment by lestrela** [comment]
Working fine!!! Up and running!!

Regards Rob and thx a lot

Cheers

Leo

Em quinta-feira, 6 de abril de 2017, Leonardo <leonardo.estrela@gmail.com>
escreveu:
