### ISSUE TITLE
error on kodi for raspberry (osmc)

### ISSUE THREAD

**Issue by Mafaldone** [mintsoft/kodi.plugin.video.pluralsight#12]
I cannot use the plugin

I get the following error:
23:55:57.866 T:1918890992  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
23:56:04.816 T:1529205744   ERROR: ExtractFrame: Could not decode a frame
23:57:31.610 T:1958892464   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
23:57:35.067 T:1404552176  NOTICE: PluralSight Duration@PostKodiInit : 0.00127220153809
23:57:35.069 T:1404552176  NOTICE: PluralSight Duration@PostSettingsLoad : 0.00285911560059
23:57:35.069 T:1404552176  NOTICE: PluralSight Duration@pre-cache check : 0.00309705734253
23:57:35.073 T:1404552176  NOTICE: PluralSight Duration@pre-API-get : 0.00665903091431
23:57:40.365 T:1404552176  NOTICE: PluralSight Duration@post-API-get : 5.29218220711
23:57:40.366 T:1404552176  NOTICE: PluralSight Duration@Re-priming DB from the API response (slow-path) : 5.29988217354
23:57:40.376 T:1404552176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('etag',)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.pluralsight/addon.py", line 396, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/plugin.video.pluralsight/addon.py", line 349, in main
                                                catalogue.update(r.headers["ETag"], r.json())
                                              File "/home/osmc/.kodi/addons/plugin.video.pluralsight/resources/lib/requests/structures.py", line 54, in __getitem__
                                                return self._store[key.lower()][1]
                                            KeyError: ('etag',)
                                            -->End of Python script error report<--
23:57:40.618 T:1958892464   ERROR: GetDirectory - Error getting plugin://plugin.video.pluralsight/
23:57:40.620 T:1958892464   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pluralsight/) failed
23:58:32.346 T:1596453872  NOTICE: ES: Client  from ::ffff: my-ip-address timed out

It seams that it is not able to locate the plugin directory. But checked and it seams to be present on /home/myuser/.kodi/addons/plugin.video.pluralsight

Thanks for support

**Comment by mintsoft** [comment]
Hmm, looking at `23:58:32.346 T:1596453872 NOTICE: ES: Client from ::ffff: my-ip-address timed out` it looks like there may be a problem with DNS resolution on your box. Is it preferring IPv6 over IPv4 or similar?

**Comment by Mafaldone** [comment]
Hi the DNS resolution it is working fine.
 I manually changed the ip to a placeholder /<my-ip-address/> (i didn't want to share my ip).

I think the issue is related with the method for getting the plugin directory, Did yopu tested on osmc installation (raspberry) ? Or did you tested it on a Android base installation?

10x for the answer :)

**Comment by mintsoft** [comment]
I've tested on neither; I usually test on Windows 10 and OpenElec. If i get a chance this weekend I'll try out osmc on a pi and see if the problem occurs for me too

The `23:57:40.620 T:1958892464 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pluralsight/) failed` error is what KODI throws whenever its unable to display a list from a plugin (it treats the plugin like a filesystem, hence the weird error)

**Comment by bengtsod** [comment]
Had the same problem last weekend, "solved" by repriming the db at plugin start every time and ignoring etag and cache. The response is fine, just no etag header? Gets one through curl though so might be something else, just wanted to get the plugin running again so didn't spend to much time on it. Just thought I'd mention it, might be wrong but not checking etag solved the problem for me.

**Comment by bengtsod** [comment]
Might mention that I'm running ubuntu 17.10 prealpha and kodi d0a790d408 :)

**Comment by mintsoft** [comment]
@bengtsod Interesting, thanks for that information. I've not seen that particular behaviour. Although I'm surprised you found the plugin usable without the cache as the pluralsight API returns >35MiB of JSON on every request, its a right performance killer

**Comment by bengtsod** [comment]
It only takes about 10-15 seconds for me to download, parse, and store the data. Got a pretty good connection so for me the cache is only a nice to have. Great plugin, with or without cache :-)

**Comment by mintsoft** [comment]
FYI: I've got this reproduced now so I'm just working through what's going on. It looks like the Pluralsight API no longer returns the etag in the response for some reason.

**Comment by asilverman** [comment]
I am reproducing the same issue on windows...  any ETA on a fix?

Kodi Log:

16:16:43.146 T:7780  NOTICE: PluralSight Duration@PostKodiInit : 0.0
16:16:43.147 T:7780  NOTICE: PluralSight Duration@PostSettingsLoad : 0.000999927520752
16:16:43.147 T:7780  NOTICE: PluralSight Duration@pre-cache check : 0.000999927520752
16:16:43.148 T:7780  NOTICE: PluralSight Duration@pre-API-get : 0.0019998550415
16:16:45.251 T:7780  NOTICE: PluralSight Duration@post-API-get : 2.10500001907
16:16:45.251 T:7780  NOTICE: PluralSight Duration@Re-priming DB from the API response (slow-path) : 2.10500001907
16:16:45.254 T:7780   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('etag',)
                                            Traceback (most recent call last):
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.pluralsight\addon.py", line 396, in <module>
                                                main()
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.pluralsight\addon.py", line 349, in main
                                                catalogue.update(r.headers["ETag"], r.json())
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.pluralsight\resources\lib\requests\structures.py", line 54, in __getitem__
                                                return self._store[key.lower()][1]
                                            KeyError: ('etag',)
                                            -->End of Python script error report<--
16:16:45.296 T:5632   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.pluralsight/
16:16:45.297 T:5632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pluralsight/) failed

**Comment by mintsoft** [comment]
@asilverman interesting, I couldn't reproduce it on windows before. The current state of `master` (https://github.com/mintsoft/kodi.plugin.video.pluralsight) should work *around* that, if you'd like to test it. However it'll disable the cache of the API response so there'll probably be a performance hit.
