### ISSUE TITLE
Not working in kodi 17.6

### ISSUE THREAD

**Issue by kmukul123** [mintsoft/kodi.plugin.video.pluralsight#15]
its not working, is it easy to fix? I can help if needed

**Comment by mintsoft** [comment]
@kmukul123 I've had a quick look at this and the API's that it was depending on seem to have been changed. I need to get a minute to look at how the main website does it and figure out the API locations from there; help welcomed!

**Comment by rpww** [comment]
Was this issue fixed?

**Comment by mintsoft** [comment]
No, it's a massive change to their API's. Basically I think this needs rewriting and I've not had the chance yet. PR's welcome!

**Comment by rayfun** [comment]
Any updates here? Why is this plugin even still in the official Kodi repo when it's clearly broken?
Could you have it removed at least or something?

**Comment by mintsoft** [comment]
I totally forgot it was in the official repo to be honest, I'll just remove it
