### ISSUE TITLE
Possible update?

### ISSUE THREAD

**Issue by chapas** [mintsoft/kodi.plugin.video.pluralsight#16]
Hi,
will this addon recieve an update?

Thanks

**Comment by mintsoft** [comment]
Hiya,

That would be unlikely, as I said here: https://github.com/mintsoft/kodi.plugin.video.pluralsight/issues/15 the pluralsight APIs have completely changed and I don't really have the will to reverse engineer either the SPA or the android app again and then rebuild the extension.

That said, if someone else picked up the baton then I'd help out.
