### ISSUE TITLE
Continuous playback

### ISSUE THREAD

**Issue by paulojreis** [mintsoft/kodi.plugin.video.pluralsight#5]
It would be great if the add-on supported continuous playback of video content; better yet if it complied with the user's video playback setting (i.e. behave according to the setting found in "Video" -> "Playback" -> "Play next video automatically").

Each Pluralsight course has modules, and each modules is divided in short videoclips. Some of these clips are really short (less than a minute), so it quickly becomes cumbersome to reach the remote after each one and make it play the next. This would be a great usability improvement.

**Comment by mintsoft** [comment]
@paulojreis I'm not sure if you're aware of the "play from here" option on the context menu? I think that should do what you want?

**Comment by paulojreis** [comment]
@mintsoft you're right, "Play from here" works. But I only have that option if I disable "Play next video automatically" in the settings (if you have it enabled, the context menu will give you "Play only this").

So, from my understanding, it should do the "Play from here" behaviour automatically when "Play next video automatically". Technically there might be a bug. As a user, however, "Play from here" solves my problem.
