### ISSUE TITLE
was no longer working, forked to fix it

### ISSUE THREAD

**Issue by 1Dimitri** [mintsoft/kodi.plugin.video.pluralsight#6]
I had errors recently on some cheap Android TV boxes because of SSLError exceptions.
May be related to the latest maintenance at pluralsight.
so I updated the requests (and urllib3)  library and it seems to fix the issue:
https://github.com/1Dimitri/kodi.plugin.video.pluralsight

**Comment by mintsoft** [comment]
@1Dimitri Thanks! Can you do a PR for me and I'll merge it in?

**Comment by 1Dimitri** [comment]
PR opened
